pipeline {
    agent {
        docker {
            image 'docker:latest'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        IMAGE_NAME = 'giap/frontend'
        CONTAINER_NAME = 'frontend.giap.local'
        GIT_REPO = 'https://github.com/erenkarakoc/genc-is-adamlari-platformu.git'
    }

    stages {
        stage('Son Kodları Al') {
            steps {
                sh 'rm -rf genc-is-adamlari-platformu'
                sh 'git clone ${GIT_REPO}'
                sh 'cd genc-is-adamlari-platformu && git checkout main'
            }
        }

        stage('İmaj Dosyasını Oluştur') {
            steps {
                dir('genc-is-adamlari-platformu/frontend') {
                    sh 'docker build -t ${IMAGE_NAME} .'
                }
            }
        }

        stage('Mevcut Uygulamayı Sil') {
            steps {
                script {
                    def containerExists = sh(script: "docker ps -a -q -f name=${CONTAINER_NAME}", returnStdout: true).trim()
                    if (containerExists) {
                        sh "docker rm -f ${CONTAINER_NAME}"
                    }
                }
            }
        }

        stage('Yeni Uygulama Başlat') {
            steps {
                sh "docker run -d --name ${CONTAINER_NAME} ${IMAGE_NAME}"
            }
        }
    }

    post {
        always {
            echo 'İşlemler başarılı bir şekilde tamamlandı!'
        }
    }
}
